config/routes.rb
Rails.application.routes.draw do

  resources :crms
  resources :sms
  resources :appadmins
  get 'adminuser/index'

  get 'template/template'

  resources :garantia
  get 'usuarios' => 'registrar#index', as: :usuarios
  get 'administradores' => 'adminuser#index', as: :administradores
  post 'registrar/create'
  post 'adminuser/create'
  post 'appadmins/create'
  resources :subgroups
  resources :asesors
  get 'charges/index'
  post 'charges/create'
  get 'charges/show'

  resources :groups
  get 'errors/app_id'
  get 'errors/acceso'
  get 'errors/sucursal'
  get 'sucursales/index'

  get 'alertpayment/index'

  resources :payments
  get 'inicio/index'

  devise_for :supers
  devise_for :sistemas
  resources :configuracions
  resources :facturadas
  resources :pendientes
  resources :ordenes_abierta
  get 'home/index'

  resources :accesos
  devise_for :users
  resources :catalogos
  resources :apps
  namespace :api do
    namespace :v1 do
      resources :report
      resources :get_empresa, path: "empresa"
      resources :get_objetivo
      resources :get_objetivo_real, path: "objetivo_real"
      resources :get_ordenes_abiertas, path: "abiertas"
      resources :get_costo, path: "costo"
      resources :get_facturas, path: "facturadas"
      resources :get_costo_internas, path: "internas"
      resources :get_conteo_internas, path: "conteo_internas"
      resources :random_orden, path: "pronostico"
      resources :random_orden_pronosticos, path: "orden_pronostico"
      resources :get_ordenes_abiertas_internas, path: "ordenes_internas"
      resources :get_porcentaje, path: "porcentaje"
      resources :crear_ordenes, path: "crear_ordenes"
      resources :crear_facturadas, path: "crear_facturadas"
      resources :valida_app_id, path: "valida_app_id"
      resources :get_ordenes_mayores, path: "mayores"
      resources :get_fecha, path: "fecha"
      resources :test, path: "prueba"
      resources :sucursales, path: "sucursales"
      resources :get_sucursales_hyp, path: "sucursales_hyp"
      resources :get_ordenes_hyp, path: "ordenes_hyp"
      resources :general, path: "general"
      resources :get_sucursales_general, path: "general_sucursales"
      resources :get_dias, path: "dias"
      resources :get_periodos_anteriores, path: "periodos"
      resources :get_periodos_servicio, path: "periodos_servicio"
      resources :get_periodos_hyp, path: "periodos_hyp"
      resources :get_nombre_asesor, path: "obtener_nombre_asesor"
      resources :get_ordenes_abiertas_asesor, path: "obtener_ordenes_asesor"
      resources :get_ordenes_facturadas_asesor, path: "obtener_facturadas_asesor"
      resources :get_competencias, path: "obtener_competencias"
      resources :get_ordenes_viejas_asesor, path: "obtener_viejas"
      resources :crear_usuarios, path: "crea_usuario"
      resources :garantias, path: "garantias"
      resources :garantias_estatus, path: "garantias_estatus"
      resources :garantias_estatus_color, path: "garantias_color"
      resources :garantias_detalles, path: "garantias_detalles"
      resources :cierre_mes, path: "cierre_mes"
      resources :encuesta, path: "enviar_encuesta"
    end
  end

  root 'control#index'
  get 'settings' => 'configuracions#index', as: :settings
  get 'objetivos' => 'catalogos#index', as: :objetivos
  get 'home' => 'home#index', as: :home
  get 'home_hyp' => 'home#index_hyp', as: :home_hyp
  get 'general' => 'home#index_general', as: :home_general
  get 'inicio' => 'inicio#index', as: :inicio
  get 'periodos' => 'home#index_periodos', as: :periodos
  get 'asesores' => 'home#index_asesores', as: :asesores
  get 'garantias' => 'home#index_garantias', as: :garantias
  get 'pago' => 'alertpayment#index', as: :pago
  get 'sucursales' => 'sucursales#index', as: :sucursales
  get 'agencias' => 'apps#index', as: :agencias
  get 'agencias/new' => 'apps#new', as: :agencias_new
  get 'panel' => 'apps#index_sistemas', as: :panel
  get 'administracion' => 'groups#index_super', as: :administracion
  get 'nuevo_grupo' => 'groups#new', as: :group_new
  get 'nuevo_usuario' => 'registrar#create', as: :usuario_new
  get 'nuevo_admin' => 'adminuser#create', as: :nuevo_admin
  match 'usuario/:id' => 'registrar#destroy', :via => :delete, :as => :admin_destroy_user
  match 'admin/:id' => 'adminuser#destroy', :via => :delete, :as => :admin_destroy
  get 'nuevo_acceso' => 'accesos#new', as: :acceso_new
  get 'perfiles' => 'accesos#perfiles', as: :perfiles
  get 'nuevo_perfil' => 'accesos#nuevo_perfil', as: :nuevo_perfil
  get 'nuevo_perfil_postventa' => 'accesos#nuevo_perfil_postventa', as: :nuevo_perfil_postventa
  get 'nuevo_perfil_hyp' => 'accesos#nuevo_perfil_hyp', as: :nuevo_perfil_hyp
  get 'nuevo_perfil_asesores' => 'accesos#nuevo_perfil_asesores', as: :nuevo_perfil_asesores
  get 'nuevo_perfil_garantias' => 'accesos#nuevo_perfil_garantias', as: :nuevo_perfil_garantias
  get 'nueva_agencia' => 'apps#new', as: :agencia_new
  get 'asignar_asesor' => 'asesors#new', as: :asignar_new
  get 'listado_asesores' => 'asesors#index', as: :listado_asesores
  get 'choise' => 'inicio#choise', as: :choise
  
  get 'encuesta' => 'inicio#encuesta', as: :encuesta

end

app/models/acceso.rb
class Acceso < ActiveRecord::Base
  belongs_to :user
  
end

app/models/app.rb
class App < ActiveRecord::Base
	belongs_to :group
end

app/models/appadmin.rb
class Appadmin < ActiveRecord::Base
end

app/models/asesor.rb
class Asesor < ActiveRecord::Base
end

app/models/catalogo.rb
class Catalogo < ActiveRecord::Base
end

app/models/crm.rb
class Crm < ActiveRecord::Base
	validates :key, uniqueness: true
end

app/models/facturada.rb
class Facturada < ActiveRecord::Base
end

app/models/garantium.rb
class Garantium < ActiveRecord::Base
	validates :key, uniqueness: true
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :apps
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/pendiente.rb
class Pendiente < ActiveRecord::Base
	#validates :importe, format: { :with => /\A[0-9]+(\.([0-9]{1,2})?)?\z/, message: 'el importe no es un formato de válido' }
	#validates_format_of :importe , with: /\A[0-9]+(\.([0-9]{1,2})?)?\z/
	
	

end

app/models/sistema.rb
class Sistema < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         scope :existe ,-> (email) {where("email = ?", email)} 
end

app/models/sm.rb
class Sm < ActiveRecord::Base
end

app/models/subgroup.rb
class Subgroup < ActiveRecord::Base
end

app/models/super.rb
class Super < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :existe ,-> (email) {where("email = ?", email)} 
end

app/controllers/adminuser_controller.rb
class AdminuserController < ApplicationController
    skip_before_action :verify_authenticity_token

   def index
   	@usuarios = Sistema.where(:group_id => params[:group_id])
    @usuario = Sistema.where(:group_id => params[:group_id]).count
   end


  def create
      @verifica = Sistema.existe(params[:email]).count
        if @verifica == 1 
          render json: { :mensaje => "El correo " + params[:email] + " ya existe, intente con otro correo"}
        else  
          user = Sistema.new(:email => params[:email], :password => params[:password], :password_confirmation => params[:password_confirmation], :group_id => params[:group_id], :app_id => params[:app_id])
          if user.save	
             redirect_to '/administracion'
            else
          end
        end   
 	end

  def destroy
    @user = Sistema.find(params[:id])
    if @user.destroy
        redirect_to root_url, notice: "Administrador Eliminado."
    end
  end
end

app/helpers/adminuser_helper.rb
module AdminuserHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/crms_helper.rb
module CrmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sms_helper.rb
module SmsHelper
end

app/views/adminuser/create.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->  
<head>
    <meta charset="utf-8" />
    <title>Pronostic</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- ================== BEGIN BASE CSS STYLE ================== -->
    <link href="http://fonts.googleapis.com/css?family=Nunito:400,300,700" rel="stylesheet" id="fontFamilySrc" />
    <link href="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447734615/jquery-ui.min.css" rel="stylesheet" />
    <link href="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447734729/bootstrap.min.css" rel="stylesheet" />
    <link href="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447735152/animate.min.css" rel="stylesheet" />
    <link href="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447735249/style.min.css" rel="stylesheet" />
  <!-- ================== END BASE CSS STYLE ================== -->
  
  <!-- ================== BEGIN PAGE LEVEL CSS STYLE ================== -->
    <link href="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447735472/jquery.gritter.css" rel="stylesheet" />  
  <!-- ================== END PAGE LEVEL CSS STYLE ================== -->
</head>
<style type="text/css">
.content{
  margin-left: 0px!important;
}
body{
  background-color: white!important;
}
.alinear{
  width: 200px;
  height: :60px!important;
  font-size: 18px;
  border-radius: 10px;
}
.alinear:hover{
  opacity: .75;
}
  h1{
    word-wrap: break-word;
    font-size: 22px;
    margin-bottom: 10px;
font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, sans-serif;
    }  
  p{
     font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-weight: 300;
    margin: 0;
    color: hsl(0, 0%, 34%);
    line-height: 1.4615em;
  }
  a.button{
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 22px;
    text-decoration: none;
    color: white;
  }
  label {
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, sans-serif;
    word-wrap: break-word;
    font-size: 22px;
    margin-bottom: 10px;
  }
  input{
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, sans-serif;
  }
  .row{
    margin-top: 10%;
  }

</style>
<body>

  <div id="page-loader" class="page-loader fade in"><span class="spinner">Loading...</span></div>
  <!-- end #page-loader -->

  <!-- begin #page-container -->
  <div id="page-container" class="fade page-container page-header-fixed page-sidebar-fixed page-with-two-sidebar page-with-footer">
    <!-- begin #header -->
    <div id="header" class="header navbar navbar-default navbar-fixed-top">
      <!-- begin container-fluid -->
      <div class="container-fluid">
        <!-- begin mobile sidebar expand / collapse button -->
        <div class="navbar-header">
          <a href="/" class="navbar-brand"><%= image_tag("logo.png", size: "150x27") %></a>
          <button type="button" class="navbar-toggle" data-click="sidebar-toggled">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <!-- end mobile sidebar expand / collapse button -->
        
        <!-- begin navbar-right -->
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown navbar-user">
            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
              <span class="hidden-xs"><%= current_super.email %></span> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu pull-right">
              <li><a href="/users/edit">Seguridad</a></li>
              <li class="divider"></li>
              <li><%= link_to "Cerrar sesión", destroy_super_session_path, method: :delete  %></li>
            </ul>
          </li>
        </ul>
        <!-- end navbar-right -->
      </div>
      <!-- end container-fluid -->
    </div>
    <!-- end #header -->
    
    <!-- begin #content -->
  <div id="content" class="content">          

   <div class="row">
                    <!-- begin col-2 -->
      <div class="col-md-1"></div>
        <div class="col-md-4">
          <h1> Crear usuarios administradores </h1>
          <p>Esta opción te permiete crear los usuarios que usaran la herramienta. </p>
        </div>
        <div class="col-md-6">
          <div class="panel-body">

               <%= form_tag controller: "adminuser", action:  "create", method: "post" do %>

          <div class="field">
            <%= label_tag 'Correo electronico empresarial' %><br />
            <%= text_field_tag :email,nil,:required => true , :class => "form-control", :placeholder => "example@empresa.com"  %>
          </div>

          <div class="field">
            <%= label_tag 'Ingresa una contraseña' %>
            <% if @validatable %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= password_field_tag :password, nil,:required => true, :class => "form-control tamano", :placeholder => "La contraseña debe tener 8 caracteres como minimo" %>
          </div>

          <div class="field">
            <%= label_tag 'Escribe nuevamente la contraseña' %><br />
            <%= password_field_tag :password_confirmation, nil,:required => true, :class => "form-control tamano", :placeholder => "La contraseña debe tener 8 caracteres como minimo" %>
          </div>
          <div class="field">
            <%= hidden_field_tag :group_id, params[:group_id], :class => "form-control tamano" %>
          </div>
          <div class="field">
            <%= hidden_field_tag :app_id, params[:app_id], :class => "form-control tamano" %>
          </div>
               
                <div class="actions">
                  <%= submit_tag "Crear",:class=>"widget widget-stat bg-primary text-white alinear button"  %>
                </div>
              <% end %>

              <hr/>
          </div>
        </div>
        <div class="col-md-1">
        </div>         <!-- end col-4 -->
      </div>
                
      </div>    
</div>

            <div id="footer" class="footer">
                <span class="pull-right">
                    <a href="javascript:;" class="btn-scroll-to-top" data-click="scroll-top">
                        <i class="fa fa-arrow-up"></i> <span class="hidden-xs">Back to Top</span>
                    </a>
                </span>
                &copy; 2015 <b>vianse</b> All Right Reserved
            </div>
            <!-- end #footer -->
    </div>
  </div>
  <!-- end page container -->

<!-- ================== BEGIN BASE JS ================== -->
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447732895/jquery-1.9.1.js"></script>
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733033/jquery-migrate-1.1.0.min.js"></script>
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733159/jquery-ui.min.js"></script>
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733251/bootstrap.min.js"></script>
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733386/jquery.slimscroll.min.js"></script>
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733489/jquery.cookie.js"></script>
  <!-- ================== END BASE JS ================== -->
  
  <!-- ================== BEGIN PAGE LEVEL JS ================== -->
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733913/bootstrap_calendar.min.js"></script>
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733996/jquery.sparkline.min.js"></script>
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447734296/jquery.gritter.js"></script>
    <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447734361/page-index.demo.js"></script>
    <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733809/demo.js"></script>
    <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447732638/apps.js"></script>
  <!-- ================== END PAGE LEVEL JS ================== -->
  
  <script>
    $(document).ready(function() {
        App.init();

    });
  </script>
</body data-no-turbolink data-no-transition-cache>
</html>


<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/react.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/JSXTransformer.js"></script>
<script src="https://rawgit.com/arqex/react-json/master/build/Json.js"></script>
<script src="//cdn.jsdelivr.net/refluxjs/0.2.11/reflux.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

app/views/adminuser/index.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->  
<head>
    <meta charset="utf-8" />
    <title>Pronostic</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- ================== BEGIN BASE CSS STYLE ================== -->
    <link href="http://fonts.googleapis.com/css?family=Nunito:400,300,700" rel="stylesheet" id="fontFamilySrc" />
    <link href="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447734615/jquery-ui.min.css" rel="stylesheet" />
    <link href="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447734729/bootstrap.min.css" rel="stylesheet" />
    <link href="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447735152/animate.min.css" rel="stylesheet" />
    <link href="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447735249/style.min.css" rel="stylesheet" />
  <!-- ================== END BASE CSS STYLE ================== -->
  
  <!-- ================== BEGIN PAGE LEVEL CSS STYLE ================== -->
    <link href="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447735472/jquery.gritter.css" rel="stylesheet" />  
  <!-- ================== END PAGE LEVEL CSS STYLE ================== -->
</head>
<style type="text/css">
.content{
  margin-left: 0px!important;
}
body{
  background-color: white!important;
}
.alinear{
  width: 200px;
  height: :60px!important;
  font-size: 18px;
  border-radius: 10px;
  margin-top: 55px;
  margin-left: 10%;
}
.alinear:hover{
  opacity: .75;
}
  h1{
    word-wrap: break-word;
    font-size: 22px;
    margin-bottom: 10px;
font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, sans-serif;
    }  
  p{
     font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-weight: 300;
    margin: 0;
    color: hsl(0, 0%, 34%);
    line-height: 1.4615em;
  }
  a.button{
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 22px;
    text-decoration: none;
    color: white;
  }
  .row{
    margin-top: 10%;
  }

  strong{
    color: hsl(0, 0%, 33%);
    display: inline;
    font-size: 18px;
    font-weight: 700;
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, sans-serif;
  }
  .link {
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 14px;
    line-height: 14px;
    margin-right: 20px;
    margin-top: -5px;
    text-decoration: none!important;
    color: hsl(202, 100%, 38%)!important;
  }
.table>thead>tr>th {
    border-style: none;
    border-bottom: none!important;
}
.row{
  margin-top: 10%!important;
}
.nobordes{
  border-style: none!important;
}
td{
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, sans-serif;
}
a.blanco{
  color: white;
}
</style>
<body>

  <div id="page-loader" class="page-loader fade in"><span class="spinner">Loading...</span></div>
  <!-- end #page-loader -->

  <!-- begin #page-container -->
  <div id="page-container" class="fade page-container page-header-fixed page-sidebar-fixed page-with-two-sidebar page-with-footer">
    <!-- begin #header -->
    <div id="header" class="header navbar navbar-default navbar-fixed-top">
      <!-- begin container-fluid -->
      <div class="container-fluid">
        <!-- begin mobile sidebar expand / collapse button -->
        <div class="navbar-header">
          <a href="/" class="navbar-brand"><%= image_tag("logo.png", size: "150x27") %></a>
          <button type="button" class="navbar-toggle" data-click="sidebar-toggled">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <!-- end mobile sidebar expand / collapse button -->
        
        <!-- begin navbar-right -->
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown navbar-user">
            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
              <span class="hidden-xs"><%= current_super.email %></span> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu pull-right">
              <li><a href="/users/edit">Seguridad</a></li>
              <li class="divider"></li>
              <li><%= link_to "Cerrar sesión", destroy_super_session_path, method: :delete  %></li>
            </ul>
          </li>
        </ul>
        <!-- end navbar-right -->
      </div>
      <!-- end container-fluid -->
    </div>
    <!-- end #header -->
    
    <!-- begin #content -->
  <div id="content" class="content">  

     

   <h1>Usuarios</h1>
   <div class="panel">
                 <div class="panel-heading">
                  <a href="/nuevo_admin?group_id=" id="agencias" class="btn btn-lg btn-info blanco">
                            <i class="fa fa-automobile pull-left"></i>
                                    Nuevo Administrador<br>
                                    
                     </a>
                    <a href="/administracion" id="back" class="btn btn-lg btn-danger blanco">
                            <i class="fa fa-reply pull-left"></i>
                                    Regresar<br>
                                    
                      </a>

                    
                  </div>
                  <div class="table-responsive">
                        <table class="table table-bordered table-hover table-striped table-td-valign-middle">
                               <thead>
                                <tr>
                                <th>Correo electronico del usuario</th>
                                <th colspan="3"></th>
                              </tr>
                            </thead>
                            <tbody>
                              <% @usuarios.each do |usuarios| %>
                                <tr>
                                  <td><strong><%= usuarios.email %></strong></td>
                                  <td><%= link_to "Eliminar", admin_destroy_path(usuarios.id), method: :delete, data: { confirm: "Estas seguro de que quieres eliminar este usuario" } %></td>

                                </tr>

                              <% end %>
                            </tbody>
                          </table> 
            </div>
        </div>


     <br>

    <!--<%= link_to 'Crear grupo', group_new_path ,:class=>"btn btn-success m-r-5 m-b-5" %>--> 
    <!-- begin #page-loader -->   

  
      </div>    
</div>

            <div id="footer" class="footer">
                <span class="pull-right">
                    <a href="javascript:;" class="btn-scroll-to-top" data-click="scroll-top">
                        <i class="fa fa-arrow-up"></i> <span class="hidden-xs">Back to Top</span>
                    </a>
                </span>
                &copy; 2015 <b>vianse</b> All Right Reserved
            </div>
            <!-- end #footer -->
    </div>
  </div>
  <!-- end page container -->

<!-- ================== BEGIN BASE JS ================== -->
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447732895/jquery-1.9.1.js"></script>
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733033/jquery-migrate-1.1.0.min.js"></script>
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733159/jquery-ui.min.js"></script>
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733251/bootstrap.min.js"></script>
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733386/jquery.slimscroll.min.js"></script>
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733489/jquery.cookie.js"></script>
  <!-- ================== END BASE JS ================== -->
  
  <!-- ================== BEGIN PAGE LEVEL JS ================== -->
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733913/bootstrap_calendar.min.js"></script>
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733996/jquery.sparkline.min.js"></script>
  <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447734296/jquery.gritter.js"></script>
    <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447734361/page-index.demo.js"></script>
    <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447733809/demo.js"></script>
    <script src="https://res.cloudinary.com/dnubgpeun/raw/upload/v1447732638/apps.js"></script>
  <!-- ================== END PAGE LEVEL JS ================== -->
  
  <script>
    $(document).ready(function() {
        App.init();

    });


var getUrlParameter = function getUrlParameter(sParam) {
    var sPageURL = decodeURIComponent(window.location.search.substring(1)),
        sURLVariables = sPageURL.split('&'),
        sParameterName,
        i;

    for (i = 0; i < sURLVariables.length; i++) {
        sParameterName = sURLVariables[i].split('=');

        if (sParameterName[0] === sParam) {
            return sParameterName[1] === undefined ? true : sParameterName[1];
            }
        }
    };
        var grupo = getUrlParameter('group_id');
        var app_id = getUrlParameter('app_id');


        var url = "/nuevo_admin?group_id=" + grupo; 
        var element = document.getElementById('agencias');
        element.setAttribute("href",url)

         var url1 = "/administracion"; 
         var element = document.getElementById('back');
         element.setAttribute("href",url1)


  </script>
</body data-no-turbolink data-no-transition-cache>
</html>


<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/react.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/JSXTransformer.js"></script>
<script src="https://rawgit.com/arqex/react-json/master/build/Json.js"></script>
<script src="//cdn.jsdelivr.net/refluxjs/0.2.11/reflux.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">