config/routes.rb
Rails.application.routes.draw do

  resources :crms
  resources :sms
  resources :appadmins
  get 'adminuser/index'

  get 'template/template'

  resources :garantia
  get 'usuarios' => 'registrar#index', as: :usuarios
  get 'administradores' => 'adminuser#index', as: :administradores
  post 'registrar/create'
  post 'adminuser/create'
  post 'appadmins/create'
  resources :subgroups
  resources :asesors
  get 'charges/index'
  post 'charges/create'
  get 'charges/show'

  resources :groups
  get 'errors/app_id'
  get 'errors/acceso'
  get 'errors/sucursal'
  get 'sucursales/index'

  get 'alertpayment/index'

  resources :payments
  get 'inicio/index'

  devise_for :supers
  devise_for :sistemas
  resources :configuracions
  resources :facturadas
  resources :pendientes
  resources :ordenes_abierta
  get 'home/index'

  resources :accesos
  devise_for :users
  resources :catalogos
  resources :apps
  namespace :api do
    namespace :v1 do
      resources :report
      resources :get_empresa, path: "empresa"
      resources :get_objetivo
      resources :get_objetivo_real, path: "objetivo_real"
      resources :get_ordenes_abiertas, path: "abiertas"
      resources :get_costo, path: "costo"
      resources :get_facturas, path: "facturadas"
      resources :get_costo_internas, path: "internas"
      resources :get_conteo_internas, path: "conteo_internas"
      resources :random_orden, path: "pronostico"
      resources :random_orden_pronosticos, path: "orden_pronostico"
      resources :get_ordenes_abiertas_internas, path: "ordenes_internas"
      resources :get_porcentaje, path: "porcentaje"
      resources :crear_ordenes, path: "crear_ordenes"
      resources :crear_facturadas, path: "crear_facturadas"
      resources :valida_app_id, path: "valida_app_id"
      resources :get_ordenes_mayores, path: "mayores"
      resources :get_fecha, path: "fecha"
      resources :test, path: "prueba"
      resources :sucursales, path: "sucursales"
      resources :get_sucursales_hyp, path: "sucursales_hyp"
      resources :get_ordenes_hyp, path: "ordenes_hyp"
      resources :general, path: "general"
      resources :get_sucursales_general, path: "general_sucursales"
      resources :get_dias, path: "dias"
      resources :get_periodos_anteriores, path: "periodos"
      resources :get_periodos_servicio, path: "periodos_servicio"
      resources :get_periodos_hyp, path: "periodos_hyp"
      resources :get_nombre_asesor, path: "obtener_nombre_asesor"
      resources :get_ordenes_abiertas_asesor, path: "obtener_ordenes_asesor"
      resources :get_ordenes_facturadas_asesor, path: "obtener_facturadas_asesor"
      resources :get_competencias, path: "obtener_competencias"
      resources :get_ordenes_viejas_asesor, path: "obtener_viejas"
      resources :crear_usuarios, path: "crea_usuario"
      resources :garantias, path: "garantias"
      resources :garantias_estatus, path: "garantias_estatus"
      resources :garantias_estatus_color, path: "garantias_color"
      resources :garantias_detalles, path: "garantias_detalles"
      resources :cierre_mes, path: "cierre_mes"
      resources :encuesta, path: "enviar_encuesta"
    end
  end

  root 'control#index'
  get 'settings' => 'configuracions#index', as: :settings
  get 'objetivos' => 'catalogos#index', as: :objetivos
  get 'home' => 'home#index', as: :home
  get 'home_hyp' => 'home#index_hyp', as: :home_hyp
  get 'general' => 'home#index_general', as: :home_general
  get 'inicio' => 'inicio#index', as: :inicio
  get 'periodos' => 'home#index_periodos', as: :periodos
  get 'asesores' => 'home#index_asesores', as: :asesores
  get 'garantias' => 'home#index_garantias', as: :garantias
  get 'pago' => 'alertpayment#index', as: :pago
  get 'sucursales' => 'sucursales#index', as: :sucursales
  get 'agencias' => 'apps#index', as: :agencias
  get 'agencias/new' => 'apps#new', as: :agencias_new
  get 'panel' => 'apps#index_sistemas', as: :panel
  get 'administracion' => 'groups#index_super', as: :administracion
  get 'nuevo_grupo' => 'groups#new', as: :group_new
  get 'nuevo_usuario' => 'registrar#create', as: :usuario_new
  get 'nuevo_admin' => 'adminuser#create', as: :nuevo_admin
  match 'usuario/:id' => 'registrar#destroy', :via => :delete, :as => :admin_destroy_user
  match 'admin/:id' => 'adminuser#destroy', :via => :delete, :as => :admin_destroy
  get 'nuevo_acceso' => 'accesos#new', as: :acceso_new
  get 'perfiles' => 'accesos#perfiles', as: :perfiles
  get 'nuevo_perfil' => 'accesos#nuevo_perfil', as: :nuevo_perfil
  get 'nuevo_perfil_postventa' => 'accesos#nuevo_perfil_postventa', as: :nuevo_perfil_postventa
  get 'nuevo_perfil_hyp' => 'accesos#nuevo_perfil_hyp', as: :nuevo_perfil_hyp
  get 'nuevo_perfil_asesores' => 'accesos#nuevo_perfil_asesores', as: :nuevo_perfil_asesores
  get 'nuevo_perfil_garantias' => 'accesos#nuevo_perfil_garantias', as: :nuevo_perfil_garantias
  get 'nueva_agencia' => 'apps#new', as: :agencia_new
  get 'asignar_asesor' => 'asesors#new', as: :asignar_new
  get 'listado_asesores' => 'asesors#index', as: :listado_asesores
  get 'choise' => 'inicio#choise', as: :choise
  
  get 'encuesta' => 'inicio#encuesta', as: :encuesta

end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_sistema!, :except => [:index]
  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:app_id,:esquema, :importe, :fechapago,:fechavencimiento, :diasalerta,:diascorteacceso, :estatus)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :app_id %><br>
    <%= f.text_field :app_id %>
  </div>
  <div class="field">
    <%= f.label :esquema %><br>
    <%= f.text_field :esquema %>
  </div>
  <div class="field">
    <%= f.label :importe %><br>
    <%= f.text_field :importe %>
  </div>
  <div class="field">
    <%= f.label :fechapago %><br>
    <%= f.date_select :fechapago %>
  </div>
  <div class="field">
    <%= f.label :fechavencimiento %><br>
    <%= f.date_select :fechavencimiento %>
  </div>
  <div class="field">
    <%= f.label :diasalerta %><br>
    <%= f.text_field :diasalerta %>
  </div>
  <div class="field">
    <%= f.label :diascorteacceso %><br>
    <%= f.text_field :diascorteacceso %>
  </div>
  <div class="field">
    <%= f.label :estatus %><br>
    <%= f.number_field :estatus %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
  <!-- begin navbar-right -->
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown navbar-user">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="hidden-xs"><%= current_sistema.email %></span> <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="/sistemas/edit">Seguridad</a></li>
                            <li class="divider"></li>
                            <li><%= link_to "Cerrar sesión", destroy_sistema_session_path, method: :delete  %></li>
                        </ul>
                    </li>
                </ul>
<p id="notice"><%= notice %></p>

<h1>Listing Payments</h1>

<table>
  <thead>
    <tr>
      <th>App</th>
      <th>Importe</th>
      <th>Fecha</th>
      <th>Dias</th>
      <th>Estatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.app_id %></td>
        <td><%= payment.importe %></td>
        <td><%= payment.fecha %></td>
        <td><%= payment.dias %></td>
        <td><%= payment.estatus %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>App:</strong>
  <%= @payment.app_id %>
</p>

<p>
  <strong>Importe:</strong>
  <%= @payment.importe %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @payment.fecha %>
</p>

<p>
  <strong>Dias:</strong>
  <%= @payment.dias %>
</p>

<p>
  <strong>Estatus:</strong>
  <%= @payment.estatus %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>